name: Model Training CICD

# Permissions required
permissions:
  id-token: write
  contents: write

# Trigger workflow on push to any branch
on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Train the model
      - name: Train model
        run: |
          python Train_model.py

      # Step 5: Generate combined report for CML
      - name: Generate report
        run: |
          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
          
          cat report.md report1.md >> combined_file.md

      # Step 6: Post report as comment (requires CML)
      - name: Comment report on PR
        uses: iterative/cml@v1
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create combined_file.md
