name: Model Training CICD

permissions:
  id-token: write
  contents: write

on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python Train_model.py

      - name: Generate Reports
        run: |
          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md

          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md

          cat report.md report1.md >> combined_file.md

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create combined_file.md
